#################################
#####        Setters        #####
#################################

set -g prefix C-Space
set -g set-clipboard on
set -g mouse on
set -g detach-on-destroy off
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal xterm-256color
unbind x
unbind ','

##################################
#####      Key Bindings      #####
##################################

bind R source-file ~/dotfiles/tmux/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."
bind v split-window -h  # ||
bind h split-window -v  # --
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind H  previous-window
bind L next-window
bind x kill-pane
bind r command-prompt -I "#W" "rename-window '%%'"
